### PR TITLE
Blog Details Page

### PR DESCRIPTION
**Pull request by MKrick**

### CODE REVIEW

**Comment by tomfriedhof** [comment]
@MKrick can you add a screenshot?

**Comment by MKrick** [comment]
blog-listing
wires-code-block

**Comment by MKrick** [comment]
wireframe_001

**Comment by martha89** [comment]
Thanks @MKrick for updating this. I added my feedback on https://activelamp.atlassian.net/wiki/display/AC/Blog+and+Video+Post.

**Comment by martha89** [comment]
Also since this PR holds the listing page, I left my feedback here: https://activelamp.atlassian.net/wiki/display/AC/Blog+and+Video+Listing+page?focusedCommentId=61341721#comment-61341721

**Pull request merged**
